title: 
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: rouge
incremental: true
jekyll_pages_api_search:
    placeholder: Search
    index_fields: {title: {boost: 10}, tags: {boost: 10}, url: {boost: 5}, body: null}
collections:
    pages: {output: true, permalink: '/:path/'}
excerpt_separator: '<!-- more -->'
exclude:
    - CONTRIBUTING.md
    - COPYING.txt
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
    - Rakefile
    - Vagrantfile
    - bower.json
    - bower_components
    - coverage
    - deploy
    - go
    - pages/private/README.md
    - vendor
permalink: pretty
tag_dir: tags
tag_title_prefix: '#'
sass:
    sass_dir: assets/_sass
    style: compressed
assets:
    js_compressor: uglifier
    css_compressor: sass
    sources: [assets/js, assets/css]
    cache: true
description: 'The go-to place for all team information '
private_data_path: _data/private
team_img_dir: assets/images/team
missing_team_member_img: avatar_blank.png
guest_user_img: logo-18f.jpg
img_name_keys:
    - name
    - deprecated_name
photo_repository_url: 'https://18f.gsa.gov/assets/images/team/'
defaults:
    - {scope: {path: "", type: pages}, values: {layout: bare, edit_info: {repo: 18F/team-browser, branch: master}, hide_edit_link: true}}
    - {scope: {path: private, type: pages}, values: {edit_info: {repo: 18F/team-browser-pages-private, prefix: _pages/private/}, hide_edit_link: true}}
editor_url: 'https://github.com/'
midas_url: 'https://openopps.digitalgov.gov'
prose:
    rooturl: pages
    media: assets
    metadata: {pages: [{name: title, field: {element: text}}, {name: permalink, field: {element: text}}]}
google_analytics_ua: UA-48605964-24
github:
    repository: team-browser
    organization: 18F
    default_branch: 18f-pages
    api_repository: team-api.18f.gov
    api_default_branch: team-updates
jekyll_get:
    - {data: team_raw, json: 'https://team-api.18f.gov/public/api/team/', cache: false}
    - {data: locations_raw, json: 'https://team-api.18f.gov/public/api/locations/', cache: false}
    - {data: projects_raw, json: 'https://team-api.18f.gov/public/api/projects/', cache: false}
    - {data: departments_raw, json: 'https://team-api.18f.gov/public/api/departments/', cache: false}
    - {data: working_groups_raw, json: 'https://team-api.18f.gov/public/api/working-groups/', cache: false}
    - {data: guilds_raw, json: 'https://team-api.18f.gov/public/api/guilds/', cache: false}
    - {data: skills_raw, json: 'https://team-api.18f.gov/public/api/skills/', cache: false}
    - {data: interests_raw, json: 'https://team-api.18f.gov/public/api/interests/', cache: false}
