"""empty message

Revision ID: 9b17f4ea432b
Revises: 6150945834d7
Create Date: 2017-01-18 14:11:14.814259

"""

# revision identifiers, used by Alembic.
revision = '9b17f4ea432b'
down_revision = '6150945834d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'throw_away_parameter')
    op.add_column('users', sa.Column('t', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 't')
    op.add_column('site_visits', sa.Column('throw_away_parameter', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
